Repository cpp-css/frontEndFall2020, pull requests merged in 2020-10, with the labels that each got.

#1 Added React-Navigation and provided some examples
  .eslintrc.js
  App.js
  README.md
  android/app/src/main/java/com/frontendfall2020/MainApplication.java
  android/settings.gradle
  components/Box/Box.component.js
  components/Box/Box.styles.js
  index.js
  ios/Podfile
  package-lock.json
  package.json
  screens/Home/Home.component.js
  screens/Home/Home.styles.js
  screens/SignIn/SignIn.component.js
  screens/SignIn/SignIn.styles.js
Labels: enhancement

#3 Added React-Navigation
  README.md
  screens/Home/Home.component.js
Labels: enhancement

#9 Fixed Login button bug and changed indents to 4
  screens/Home/Home.component.js
  screens/Home/Home.styles.js
  screens/Login/Login.component.js
  screens/SignUp/SignUp.styles.js
Labels: bugfixes, design

#8 Implement UI design to the application
  App.js
  components/Btn/Btn.js
  package-lock.json
  screens/Home/Home.component.js
  screens/Home/Home.styles.js
  screens/Login/Login.component.js
  screens/Login/Login.styles.js
  screens/SignIn/SignIn.component.js
  screens/SignUp/SignUp.component.js
  screens/SignUp/SignUp.styles.js
Labels: design

#16 Implemented Swipe Feature for Events Browser, Fix File Structure & Refactor Codebase
  .eslintrc.js
  .prettierrc.js
  App.js
  android/app/build.gradle
  assets/images/Blizzard.png
  assets/images/CTF.png
  assets/images/CareerCenterWorkshop.jpg
  components/Box/Box.component.js
  components/Box/Box.styles.js
  components/Btn/Btn.js
  components/EventCard/EventCard.component.js
  components/EventCard/EventCard.styles.js
  components/MainButton/MainButton.component.js
  components/MainButton/MainButton.styles.js
  package-lock.json
  package.json
  screens/Clubs/Clubs.component.js
  screens/Clubs/Clubs.styles.js
  screens/Events/Events.component.js
  screens/Events/Events.styles.js
  screens/Feed/Feed.component.js
  screens/Feed/Feed.styles.js
  screens/Home/Home.component.js
  screens/Home/Home.styles.js
  screens/Login/Login.component.js
  screens/Main/Main.component.js
  screens/Main/tabbar/directory.js
  screens/Main/tabbar/home.js
  screens/Main/tabbar/news.js
  screens/Navigation/Navigation.component.js
  screens/Navigation/Navigation.styles.js
  screens/Navigation/contact.js
  screens/Profile/Profile.component.js
  screens/Profile/Profile.styles.js
  screens/SignUp/SignUp.component.js
Labels: enhancement

#22 Fixed bug: Can't find variable: MainButton and 4-space Indents
  App.js
  screens/Events/Events.component.js
  screens/Home/Home.component.js
  screens/Navigation/contact.js
  screens/SignUp/SignUp.component.js
Labels: bug

#23 update feed component
  components/EventCard/EventCard.styles.js
  components/Home.js
  screens/Feed/Feed.component.js
  screens/Feed/Feed.styles.js
Labels: enhancement

#28 Fixed Sign Up Password Bug; Added email input validation for Login
  screens/Login/Login.component.js
  screens/SignUp/SignUp.component.js
Labels: bug, bugfixes, enhancement

#32 Refactor components, added Ben's Profile components.
  App.js
  components/MainButton/MainButton.component.js
  components/TextLabel/TextLabel.component.js
  components/TextLabel/TextLabel.styles.js
  screens/Contact/Contact.component.js
  screens/Contact/Contact.styles.js
  screens/Login/Login.component.js
  screens/Login/Login.styles.js
  screens/Navigation/contact.js
  screens/Profile/Profile.component.js
  screens/Profile/Profile.styles.js
  screens/SignUp/SignUp.component.js
  screens/SignUp/SignUp.styles.js
  screens/UserSettings/UserSettings.component.js
  screens/UserSettings/UserSettings.styles.js
Labels: bugfixes, enhancement
